version: 2
project_name: nodapt
builds:
  - binary: nodapt
    main: ./cmd/nodapt/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
      - -trimpath
    env:
      - CGO_ENABLED=0

archives:
  - files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
